# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 10:09
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('practicals', '0002_auto_20170528_0956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterTable',
        ),
        migrations.AddField(
            model_name='allsubject',
            name='stream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='practicals.StreamData'),
            preserve_default=False,
        ),
    ]
