# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicals', '0007_auto_20170528_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=2000)),
            ],
        ),
    ]
