# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicals', '0008_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
